# Generated by Django 6.0.5 on 2026-05-16 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_usuario_nick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_spotify', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('id_lastfm', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('artista', models.CharField(max_length=255)),
                ('url_capa', models.URLField(blank=True, max_length=255, null=True)),
                ('ano_lancamento', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_escutado', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_perfil', to='albuns.album')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_album', to='usuarios.perfil')),
            ],
            options={
                'ordering': ['-data_escutado'],
            },
        ),
    ]
