# Generated by Django 6.0.5 on 2026-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id_spotify',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='url_capa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
