# Generated by Django 6.0.5 on 2026-05-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0002_alter_album_id_spotify_alter_album_url_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='termo_busca',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
