# Generated by Django 6.0.5 on 2026-05-16 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_usuario_nick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_clube', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('admin', models.BooleanField(default=False)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.clube')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'clube')},
            },
        ),
        migrations.AddField(
            model_name='clube',
            name='membros',
            field=models.ManyToManyField(related_name='clubes_que_participo', through='clubes.MembroGrupo', to='usuarios.perfil'),
        ),
    ]
