# Generated by Django 6.0.5 on 2026-05-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0002_alter_album_id_spotify_alter_album_url_capa'),
        ('clubes', '0001_initial'),
        ('usuarios', '0002_remove_usuario_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrogrupo',
            name='ultima_vez_curador',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('posicao', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albuns.album')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='clubes.clube')),
                ('sugerido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfil')),
            ],
            options={
                'ordering': ['posicao', 'adicionado_em'],
                'unique_together': {('clube', 'album')},
            },
        ),
    ]
