# Generated by Django 6.0.5 on 2026-05-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0002_alter_album_id_spotify_alter_album_url_capa'),
        ('clubes', '0002_membrogrupo_ultima_vez_curador_queue'),
        ('reviews', '0001_initial'),
        ('usuarios', '0002_remove_usuario_nick'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_clube', to='clubes.clube'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('perfil', 'album', 'clube')},
        ),
    ]
